/**
 * Created by itorrev on 4/04/14.
 */
var itvDataLoaderMongolabApp = angular.module('mongolabloaderapp', ['itvDataResource']);

/**
 * script simple para cargar los datos en una base de datos alojada en mongoLab
 * para la generación de datos de prueba se ha utilizado una herramienta online
 * llamada JSON Generator (http://www.json-generator.com/)
 * El template usado para la generación de datos es el siguiente
 */
/*
 [
     '{{repeat(105, 107)}}',
     {
         salario: '{{numeric(1000, 9000, "$0,0.00")}}',
         edad: '{{numeric(20, 60)}}',
         nombre: '{{firstName()}}',
         apellido: '{{surname()}}',
         email: '{{email()}}',
         telefono: '{{phone()}}',
         direccion: '{{numeric(01, 99)}} {{street()}}',
         ciudad: '{{city()}}',
         contratacion: '{{date(new Date(1980, 0, 1), new Date(), "YYYY-MM-dd")}}',
         departamento: function (tags) {
         var deps = ['gerencia', 'recursos humanos', 'desarrollo', 'arquitectura', 'marketing'];
            return deps[tags.numeric(0, deps.length - 1)];
         }
     }
 ]
 */
itvDataLoaderMongolabApp.controller('dataLoaderCtr', function($scope, DataResource){
    var url = 'https://api.mongolab.com/api/1/databases/itvempresa/collections/empleados/';
    var apiKeyParam = { 'apiKey': 'o_YePtBXIXDJiG1MVpacLhhVpVNvDqcC'};

    var insert = [
        {
            "salario": "$4,474.00",
            "edad": 20,
            "nombre": "Bethany",
            "apellido": "Velasquez",
            "email": "bethanyvelasquez@snorus.com",
            "telefono": "(823) 468-3658",
            "direccion": "71 Doughty Street",
            "ciudad": "Collins",
            "contratacion": "1997-10-25",
            "departamento": "arquitectura"
        },
        {
            "salario": "$3,807.00",
            "edad": 38,
            "nombre": "Chan",
            "apellido": "Curry",
            "email": "chancurry@snorus.com",
            "telefono": "(934) 472-3613",
            "direccion": "71 Kosciusko Street",
            "ciudad": "Fresno",
            "contratacion": "2000-04-06",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$1,961.00",
            "edad": 60,
            "nombre": "Deirdre",
            "apellido": "Love",
            "email": "deirdrelove@snorus.com",
            "telefono": "(817) 405-3773",
            "direccion": "43 Bartlett Place",
            "ciudad": "Wauhillau",
            "contratacion": "2005-02-20",
            "departamento": "arquitectura"
        },
        {
            "salario": "$4,828.00",
            "edad": 48,
            "nombre": "Rachael",
            "apellido": "Brown",
            "email": "rachaelbrown@snorus.com",
            "telefono": "(887) 560-3827",
            "direccion": "28 Hunterfly Place",
            "ciudad": "Dana",
            "contratacion": "2000-06-11",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$1,203.00",
            "edad": 38,
            "nombre": "Fisher",
            "apellido": "Larsen",
            "email": "fisherlarsen@snorus.com",
            "telefono": "(873) 522-3430",
            "direccion": "97 Halleck Street",
            "ciudad": "Nile",
            "contratacion": "2006-06-26",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,657.00",
            "edad": 39,
            "nombre": "Darlene",
            "apellido": "Reese",
            "email": "darlenereese@snorus.com",
            "telefono": "(939) 558-2196",
            "direccion": "24 Turner Place",
            "ciudad": "Websterville",
            "contratacion": "1984-09-30",
            "departamento": "arquitectura"
        },
        {
            "salario": "$7,963.00",
            "edad": 28,
            "nombre": "Madeleine",
            "apellido": "Stark",
            "email": "madeleinestark@snorus.com",
            "telefono": "(883) 401-3078",
            "direccion": "94 Bushwick Place",
            "ciudad": "Osmond",
            "contratacion": "1987-07-31",
            "departamento": "arquitectura"
        },
        {
            "salario": "$4,836.00",
            "edad": 40,
            "nombre": "Marie",
            "apellido": "Kirk",
            "email": "mariekirk@snorus.com",
            "telefono": "(909) 492-3368",
            "direccion": "7 Madison Place",
            "ciudad": "Forbestown",
            "contratacion": "1997-04-30",
            "departamento": "gerencia"
        },
        {
            "salario": "$3,513.00",
            "edad": 26,
            "nombre": "Rebekah",
            "apellido": "Barker",
            "email": "rebekahbarker@snorus.com",
            "telefono": "(944) 572-2669",
            "direccion": "29 Congress Street",
            "ciudad": "Grahamtown",
            "contratacion": "1984-04-04",
            "departamento": "arquitectura"
        },
        {
            "salario": "$2,760.00",
            "edad": 20,
            "nombre": "Casandra",
            "apellido": "Hogan",
            "email": "casandrahogan@snorus.com",
            "telefono": "(937) 500-2947",
            "direccion": "50 Rutherford Place",
            "ciudad": "Blairstown",
            "contratacion": "1982-09-05",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$5,841.00",
            "edad": 25,
            "nombre": "Tillman",
            "apellido": "Richards",
            "email": "tillmanrichards@snorus.com",
            "telefono": "(987) 501-2302",
            "direccion": "12 Roosevelt Place",
            "ciudad": "Clara",
            "contratacion": "1986-04-05",
            "departamento": "marketing"
        },
        {
            "salario": "$8,105.00",
            "edad": 45,
            "nombre": "Meghan",
            "apellido": "Holden",
            "email": "meghanholden@snorus.com",
            "telefono": "(926) 407-2574",
            "direccion": "46 Colby Court",
            "ciudad": "Gasquet",
            "contratacion": "2011-05-04",
            "departamento": "arquitectura"
        },
        {
            "salario": "$8,564.00",
            "edad": 60,
            "nombre": "Johnson",
            "apellido": "Kirkland",
            "email": "johnsonkirkland@snorus.com",
            "telefono": "(846) 532-2435",
            "direccion": "70 Beayer Place",
            "ciudad": "Haena",
            "contratacion": "1991-01-26",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,836.00",
            "edad": 48,
            "nombre": "Stone",
            "apellido": "Mendoza",
            "email": "stonemendoza@snorus.com",
            "telefono": "(994) 469-3163",
            "direccion": "79 Grove Street",
            "ciudad": "Galesville",
            "contratacion": "2004-10-02",
            "departamento": "arquitectura"
        },
        {
            "salario": "$6,610.00",
            "edad": 43,
            "nombre": "Clay",
            "apellido": "Skinner",
            "email": "clayskinner@snorus.com",
            "telefono": "(853) 470-2078",
            "direccion": "14 Taaffe Place",
            "ciudad": "Richford",
            "contratacion": "2006-11-04",
            "departamento": "marketing"
        },
        {
            "salario": "$1,463.00",
            "edad": 55,
            "nombre": "Cobb",
            "apellido": "Rodriguez",
            "email": "cobbrodriguez@snorus.com",
            "telefono": "(967) 464-3509",
            "direccion": "63 Bath Avenue",
            "ciudad": "Tedrow",
            "contratacion": "2012-04-21",
            "departamento": "marketing"
        },
        {
            "salario": "$1,440.00",
            "edad": 22,
            "nombre": "Bryant",
            "apellido": "Kelly",
            "email": "bryantkelly@snorus.com",
            "telefono": "(895) 474-3852",
            "direccion": "40 Taylor Street",
            "ciudad": "Bloomington",
            "contratacion": "1993-10-15",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$8,125.00",
            "edad": 52,
            "nombre": "Joan",
            "apellido": "Owens",
            "email": "joanowens@snorus.com",
            "telefono": "(919) 584-3304",
            "direccion": "40 Whitney Avenue",
            "ciudad": "Cliff",
            "contratacion": "2012-02-01",
            "departamento": "desarrollo"
        },
        {
            "salario": "$3,412.00",
            "edad": 30,
            "nombre": "Mclaughlin",
            "apellido": "Huber",
            "email": "mclaughlinhuber@snorus.com",
            "telefono": "(996) 529-3083",
            "direccion": "91 Hinckley Place",
            "ciudad": "Connerton",
            "contratacion": "2000-07-18",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$1,604.00",
            "edad": 42,
            "nombre": "Nichole",
            "apellido": "Vincent",
            "email": "nicholevincent@snorus.com",
            "telefono": "(959) 498-3976",
            "direccion": "84 Poplar Street",
            "ciudad": "Imperial",
            "contratacion": "2006-05-18",
            "departamento": "marketing"
        },
        {
            "salario": "$7,823.00",
            "edad": 55,
            "nombre": "Doyle",
            "apellido": "Murray",
            "email": "doylemurray@snorus.com",
            "telefono": "(871) 525-2099",
            "direccion": "58 Atkins Avenue",
            "ciudad": "Chaparrito",
            "contratacion": "1994-02-21",
            "departamento": "gerencia"
        },
        {
            "salario": "$8,606.00",
            "edad": 25,
            "nombre": "Billie",
            "apellido": "Newman",
            "email": "billienewman@snorus.com",
            "telefono": "(864) 523-3633",
            "direccion": "53 Buffalo Avenue",
            "ciudad": "Oretta",
            "contratacion": "2005-08-20",
            "departamento": "marketing"
        },
        {
            "salario": "$1,343.00",
            "edad": 21,
            "nombre": "Andrews",
            "apellido": "Ryan",
            "email": "andrewsryan@snorus.com",
            "telefono": "(970) 471-2529",
            "direccion": "46 Bedford Avenue",
            "ciudad": "Rosine",
            "contratacion": "1991-09-02",
            "departamento": "arquitectura"
        },
        {
            "salario": "$6,050.00",
            "edad": 21,
            "nombre": "Leanna",
            "apellido": "Shaw",
            "email": "leannashaw@snorus.com",
            "telefono": "(927) 527-3170",
            "direccion": "98 Ryder Street",
            "ciudad": "Rossmore",
            "contratacion": "2000-06-25",
            "departamento": "desarrollo"
        },
        {
            "salario": "$1,837.00",
            "edad": 39,
            "nombre": "Hurst",
            "apellido": "Ellis",
            "email": "hurstellis@snorus.com",
            "telefono": "(831) 530-3633",
            "direccion": "79 Hegeman Avenue",
            "ciudad": "Delwood",
            "contratacion": "1993-10-03",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,748.00",
            "edad": 57,
            "nombre": "Brown",
            "apellido": "Jenkins",
            "email": "brownjenkins@snorus.com",
            "telefono": "(839) 469-2150",
            "direccion": "88 Bowery Street",
            "ciudad": "Grandview",
            "contratacion": "2011-06-11",
            "departamento": "gerencia"
        },
        {
            "salario": "$7,467.00",
            "edad": 49,
            "nombre": "Nellie",
            "apellido": "Taylor",
            "email": "nellietaylor@snorus.com",
            "telefono": "(973) 456-3449",
            "direccion": "22 Herbert Street",
            "ciudad": "Smock",
            "contratacion": "1981-05-25",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,252.00",
            "edad": 27,
            "nombre": "Barron",
            "apellido": "Daniel",
            "email": "barrondaniel@snorus.com",
            "telefono": "(816) 482-2936",
            "direccion": "48 Hawthorne Street",
            "ciudad": "Gouglersville",
            "contratacion": "1998-01-26",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$3,107.00",
            "edad": 47,
            "nombre": "Hopper",
            "apellido": "Moran",
            "email": "hoppermoran@snorus.com",
            "telefono": "(966) 451-2102",
            "direccion": "27 Grace Court",
            "ciudad": "Riviera",
            "contratacion": "1984-09-06",
            "departamento": "gerencia"
        },
        {
            "salario": "$3,475.00",
            "edad": 31,
            "nombre": "Janette",
            "apellido": "Graham",
            "email": "janettegraham@snorus.com",
            "telefono": "(955) 462-3874",
            "direccion": "87 Nixon Court",
            "ciudad": "Terlingua",
            "contratacion": "1986-11-07",
            "departamento": "arquitectura"
        },
        {
            "salario": "$1,348.00",
            "edad": 22,
            "nombre": "Rosa",
            "apellido": "Mccullough",
            "email": "rosamccullough@snorus.com",
            "telefono": "(922) 553-2288",
            "direccion": "91 Beaver Street",
            "ciudad": "Savannah",
            "contratacion": "1980-12-28",
            "departamento": "marketing"
        },
        {
            "salario": "$6,018.00",
            "edad": 44,
            "nombre": "Russell",
            "apellido": "Duncan",
            "email": "russellduncan@snorus.com",
            "telefono": "(935) 461-3440",
            "direccion": "78 Matthews Court",
            "ciudad": "Sehili",
            "contratacion": "1995-10-11",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$3,919.00",
            "edad": 45,
            "nombre": "Galloway",
            "apellido": "Clements",
            "email": "gallowayclements@snorus.com",
            "telefono": "(925) 467-2246",
            "direccion": "27 Macdougal Street",
            "ciudad": "Adamstown",
            "contratacion": "2011-07-15",
            "departamento": "desarrollo"
        },
        {
            "salario": "$5,311.00",
            "edad": 45,
            "nombre": "Ofelia",
            "apellido": "Santiago",
            "email": "ofeliasantiago@snorus.com",
            "telefono": "(860) 584-3692",
            "direccion": "9 Ocean Avenue",
            "ciudad": "Cade",
            "contratacion": "1989-04-30",
            "departamento": "desarrollo"
        },
        {
            "salario": "$6,406.00",
            "edad": 50,
            "nombre": "Violet",
            "apellido": "Puckett",
            "email": "violetpuckett@snorus.com",
            "telefono": "(849) 525-3099",
            "direccion": "16 Linden Boulevard",
            "ciudad": "Riverton",
            "contratacion": "1999-08-31",
            "departamento": "desarrollo"
        },
        {
            "salario": "$6,465.00",
            "edad": 34,
            "nombre": "Collins",
            "apellido": "Wynn",
            "email": "collinswynn@snorus.com",
            "telefono": "(885) 464-2261",
            "direccion": "88 Church Lane",
            "ciudad": "Masthope",
            "contratacion": "1994-02-02",
            "departamento": "desarrollo"
        },
        {
            "salario": "$8,816.00",
            "edad": 54,
            "nombre": "Figueroa",
            "apellido": "Cannon",
            "email": "figueroacannon@snorus.com",
            "telefono": "(977) 461-3005",
            "direccion": "43 Newport Street",
            "ciudad": "Tibbie",
            "contratacion": "2009-03-23",
            "departamento": "gerencia"
        },
        {
            "salario": "$6,607.00",
            "edad": 30,
            "nombre": "Torres",
            "apellido": "Sherman",
            "email": "torressherman@snorus.com",
            "telefono": "(841) 452-3173",
            "direccion": "34 Scott Avenue",
            "ciudad": "Sperryville",
            "contratacion": "2010-01-31",
            "departamento": "gerencia"
        },
        {
            "salario": "$8,062.00",
            "edad": 55,
            "nombre": "Aline",
            "apellido": "Barron",
            "email": "alinebarron@snorus.com",
            "telefono": "(933) 594-3732",
            "direccion": "52 Anna Court",
            "ciudad": "Olney",
            "contratacion": "2002-08-06",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,385.00",
            "edad": 25,
            "nombre": "Mcleod",
            "apellido": "Schwartz",
            "email": "mcleodschwartz@snorus.com",
            "telefono": "(938) 510-3682",
            "direccion": "30 Sands Street",
            "ciudad": "Elwood",
            "contratacion": "2006-01-11",
            "departamento": "gerencia"
        },
        {
            "salario": "$5,115.00",
            "edad": 21,
            "nombre": "Paulette",
            "apellido": "Fry",
            "email": "paulettefry@snorus.com",
            "telefono": "(983) 580-2565",
            "direccion": "28 Cortelyou Road",
            "ciudad": "Westerville",
            "contratacion": "2003-01-05",
            "departamento": "marketing"
        },
        {
            "salario": "$2,588.00",
            "edad": 33,
            "nombre": "Susan",
            "apellido": "Grimes",
            "email": "susangrimes@snorus.com",
            "telefono": "(976) 406-3693",
            "direccion": "3 Nostrand Avenue",
            "ciudad": "Richmond",
            "contratacion": "1999-03-20",
            "departamento": "arquitectura"
        },
        {
            "salario": "$1,835.00",
            "edad": 39,
            "nombre": "Washington",
            "apellido": "Browning",
            "email": "washingtonbrowning@snorus.com",
            "telefono": "(894) 400-2022",
            "direccion": "17 Forrest Street",
            "ciudad": "Chical",
            "contratacion": "1995-06-29",
            "departamento": "desarrollo"
        },
        {
            "salario": "$1,939.00",
            "edad": 41,
            "nombre": "Jerri",
            "apellido": "Melton",
            "email": "jerrimelton@snorus.com",
            "telefono": "(956) 440-3488",
            "direccion": "51 Hewes Street",
            "ciudad": "Allensworth",
            "contratacion": "2002-12-14",
            "departamento": "desarrollo"
        },
        {
            "salario": "$1,351.00",
            "edad": 50,
            "nombre": "Contreras",
            "apellido": "Lindsey",
            "email": "contreraslindsey@snorus.com",
            "telefono": "(892) 573-3906",
            "direccion": "46 Dunham Place",
            "ciudad": "Florence",
            "contratacion": "1981-01-21",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$3,321.00",
            "edad": 51,
            "nombre": "Alexandra",
            "apellido": "Anderson",
            "email": "alexandraanderson@snorus.com",
            "telefono": "(918) 413-2810",
            "direccion": "19 Banner Avenue",
            "ciudad": "Waikele",
            "contratacion": "2007-03-25",
            "departamento": "desarrollo"
        },
        {
            "salario": "$2,562.00",
            "edad": 41,
            "nombre": "Beryl",
            "apellido": "Brock",
            "email": "berylbrock@snorus.com",
            "telefono": "(912) 589-3810",
            "direccion": "68 Lexington Avenue",
            "ciudad": "Chase",
            "contratacion": "1996-02-05",
            "departamento": "marketing"
        },
        {
            "salario": "$3,789.00",
            "edad": 36,
            "nombre": "Jerry",
            "apellido": "Battle",
            "email": "jerrybattle@snorus.com",
            "telefono": "(894) 432-2083",
            "direccion": "26 Cypress Court",
            "ciudad": "Cowiche",
            "contratacion": "2008-04-27",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$2,818.00",
            "edad": 31,
            "nombre": "Rosanne",
            "apellido": "Avila",
            "email": "rosanneavila@snorus.com",
            "telefono": "(865) 446-3608",
            "direccion": "34 Luquer Street",
            "ciudad": "Blanford",
            "contratacion": "2010-07-05",
            "departamento": "marketing"
        },
        {
            "salario": "$5,258.00",
            "edad": 39,
            "nombre": "Candace",
            "apellido": "Young",
            "email": "candaceyoung@snorus.com",
            "telefono": "(977) 415-2447",
            "direccion": "81 Cook Street",
            "ciudad": "Eden",
            "contratacion": "1992-09-13",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,803.00",
            "edad": 38,
            "nombre": "Yvonne",
            "apellido": "Mack",
            "email": "yvonnemack@snorus.com",
            "telefono": "(951) 472-2028",
            "direccion": "31 Perry Terrace",
            "ciudad": "Umapine",
            "contratacion": "1980-06-11",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$1,334.00",
            "edad": 44,
            "nombre": "Fields",
            "apellido": "Mooney",
            "email": "fieldsmooney@snorus.com",
            "telefono": "(895) 548-3451",
            "direccion": "43 Stryker Street",
            "ciudad": "Rivera",
            "contratacion": "2012-10-21",
            "departamento": "desarrollo"
        },
        {
            "salario": "$4,005.00",
            "edad": 59,
            "nombre": "Wagner",
            "apellido": "Pittman",
            "email": "wagnerpittman@snorus.com",
            "telefono": "(833) 495-3494",
            "direccion": "54 Kathleen Court",
            "ciudad": "Coldiron",
            "contratacion": "1980-10-17",
            "departamento": "desarrollo"
        },
        {
            "salario": "$2,541.00",
            "edad": 24,
            "nombre": "Tracie",
            "apellido": "Williams",
            "email": "traciewilliams@snorus.com",
            "telefono": "(884) 411-2465",
            "direccion": "31 Bijou Avenue",
            "ciudad": "Elliston",
            "contratacion": "1989-01-27",
            "departamento": "gerencia"
        },
        {
            "salario": "$1,758.00",
            "edad": 41,
            "nombre": "Preston",
            "apellido": "Todd",
            "email": "prestontodd@snorus.com",
            "telefono": "(814) 531-3147",
            "direccion": "77 Whitwell Place",
            "ciudad": "Savage",
            "contratacion": "1982-10-27",
            "departamento": "arquitectura"
        },
        {
            "salario": "$1,695.00",
            "edad": 54,
            "nombre": "Harris",
            "apellido": "Williamson",
            "email": "harriswilliamson@snorus.com",
            "telefono": "(852) 419-2978",
            "direccion": "31 Hamilton Walk",
            "ciudad": "Takilma",
            "contratacion": "2012-11-19",
            "departamento": "gerencia"
        },
        {
            "salario": "$6,469.00",
            "edad": 45,
            "nombre": "Elisa",
            "apellido": "White",
            "email": "elisawhite@snorus.com",
            "telefono": "(846) 576-3532",
            "direccion": "62 Brooklyn Road",
            "ciudad": "Dalton",
            "contratacion": "1987-12-25",
            "departamento": "desarrollo"
        },
        {
            "salario": "$1,219.00",
            "edad": 57,
            "nombre": "Karina",
            "apellido": "Francis",
            "email": "karinafrancis@snorus.com",
            "telefono": "(862) 444-2418",
            "direccion": "57 Manhattan Court",
            "ciudad": "Bentonville",
            "contratacion": "1982-12-25",
            "departamento": "arquitectura"
        },
        {
            "salario": "$3,416.00",
            "edad": 40,
            "nombre": "Eddie",
            "apellido": "Marks",
            "email": "eddiemarks@snorus.com",
            "telefono": "(943) 490-2563",
            "direccion": "98 Adams Street",
            "ciudad": "Marne",
            "contratacion": "2008-08-08",
            "departamento": "arquitectura"
        },
        {
            "salario": "$5,150.00",
            "edad": 52,
            "nombre": "Abby",
            "apellido": "Hudson",
            "email": "abbyhudson@snorus.com",
            "telefono": "(922) 433-3360",
            "direccion": "49 Middleton Street",
            "ciudad": "Cedarville",
            "contratacion": "2000-10-14",
            "departamento": "gerencia"
        },
        {
            "salario": "$2,481.00",
            "edad": 24,
            "nombre": "Levy",
            "apellido": "Soto",
            "email": "levysoto@snorus.com",
            "telefono": "(913) 586-3088",
            "direccion": "51 Legion Street",
            "ciudad": "Witmer",
            "contratacion": "2005-10-07",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$4,868.00",
            "edad": 28,
            "nombre": "Gina",
            "apellido": "Mclaughlin",
            "email": "ginamclaughlin@snorus.com",
            "telefono": "(892) 576-3119",
            "direccion": "50 Conduit Boulevard",
            "ciudad": "Martell",
            "contratacion": "1995-02-02",
            "departamento": "marketing"
        },
        {
            "salario": "$5,859.00",
            "edad": 31,
            "nombre": "Patty",
            "apellido": "Irwin",
            "email": "pattyirwin@snorus.com",
            "telefono": "(923) 401-2807",
            "direccion": "27 Bradford Street",
            "ciudad": "Calvary",
            "contratacion": "2005-09-26",
            "departamento": "gerencia"
        },
        {
            "salario": "$5,437.00",
            "edad": 31,
            "nombre": "Lorene",
            "apellido": "Joseph",
            "email": "lorenejoseph@snorus.com",
            "telefono": "(963) 496-3345",
            "direccion": "23 Tech Place",
            "ciudad": "Wadsworth",
            "contratacion": "1986-07-23",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$4,541.00",
            "edad": 22,
            "nombre": "Perry",
            "apellido": "Bright",
            "email": "perrybright@snorus.com",
            "telefono": "(809) 501-2429",
            "direccion": "75 Covert Street",
            "ciudad": "Hiseville",
            "contratacion": "2013-01-15",
            "departamento": "arquitectura"
        },
        {
            "salario": "$4,473.00",
            "edad": 25,
            "nombre": "Sybil",
            "apellido": "Zamora",
            "email": "sybilzamora@snorus.com",
            "telefono": "(964) 459-2620",
            "direccion": "2 Ross Street",
            "ciudad": "Sena",
            "contratacion": "2004-06-01",
            "departamento": "arquitectura"
        },
        {
            "salario": "$5,128.00",
            "edad": 50,
            "nombre": "Millie",
            "apellido": "Malone",
            "email": "milliemalone@snorus.com",
            "telefono": "(998) 432-3556",
            "direccion": "83 Gain Court",
            "ciudad": "Rodanthe",
            "contratacion": "2004-10-21",
            "departamento": "desarrollo"
        },
        {
            "salario": "$6,679.00",
            "edad": 33,
            "nombre": "Stout",
            "apellido": "Moore",
            "email": "stoutmoore@snorus.com",
            "telefono": "(910) 517-2986",
            "direccion": "40 Orange Street",
            "ciudad": "Yonah",
            "contratacion": "1998-06-16",
            "departamento": "arquitectura"
        },
        {
            "salario": "$4,765.00",
            "edad": 52,
            "nombre": "Holcomb",
            "apellido": "Gibbs",
            "email": "holcombgibbs@snorus.com",
            "telefono": "(856) 485-3414",
            "direccion": "26 Kent Street",
            "ciudad": "Hemlock",
            "contratacion": "1988-04-29",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$6,508.00",
            "edad": 23,
            "nombre": "Elvira",
            "apellido": "Freeman",
            "email": "elvirafreeman@snorus.com",
            "telefono": "(961) 516-2559",
            "direccion": "67 Joralemon Street",
            "ciudad": "Laurelton",
            "contratacion": "2000-07-27",
            "departamento": "arquitectura"
        },
        {
            "salario": "$5,293.00",
            "edad": 50,
            "nombre": "Jody",
            "apellido": "Ochoa",
            "email": "jodyochoa@snorus.com",
            "telefono": "(878) 499-3545",
            "direccion": "41 Gilmore Court",
            "ciudad": "Camas",
            "contratacion": "2000-01-02",
            "departamento": "gerencia"
        },
        {
            "salario": "$5,814.00",
            "edad": 21,
            "nombre": "Church",
            "apellido": "Duran",
            "email": "churchduran@snorus.com",
            "telefono": "(856) 542-3280",
            "direccion": "72 Clarendon Road",
            "ciudad": "Helen",
            "contratacion": "1998-04-26",
            "departamento": "arquitectura"
        },
        {
            "salario": "$8,282.00",
            "edad": 25,
            "nombre": "Shauna",
            "apellido": "Fitzpatrick",
            "email": "shaunafitzpatrick@snorus.com",
            "telefono": "(817) 486-3308",
            "direccion": "23 Division Avenue",
            "ciudad": "Richville",
            "contratacion": "1988-02-29",
            "departamento": "gerencia"
        },
        {
            "salario": "$3,993.00",
            "edad": 52,
            "nombre": "Neva",
            "apellido": "Gates",
            "email": "nevagates@snorus.com",
            "telefono": "(837) 544-3837",
            "direccion": "28 Ingraham Street",
            "ciudad": "Oasis",
            "contratacion": "2000-06-16",
            "departamento": "arquitectura"
        },
        {
            "salario": "$5,455.00",
            "edad": 26,
            "nombre": "Dona",
            "apellido": "Burton",
            "email": "donaburton@snorus.com",
            "telefono": "(867) 472-2947",
            "direccion": "72 Ira Court",
            "ciudad": "Windsor",
            "contratacion": "2009-07-11",
            "departamento": "desarrollo"
        },
        {
            "salario": "$4,794.00",
            "edad": 54,
            "nombre": "Valeria",
            "apellido": "Ray",
            "email": "valeriaray@snorus.com",
            "telefono": "(942) 426-2844",
            "direccion": "24 Stuyvesant Avenue",
            "ciudad": "Grapeview",
            "contratacion": "1986-12-29",
            "departamento": "desarrollo"
        },
        {
            "salario": "$6,958.00",
            "edad": 38,
            "nombre": "Eaton",
            "apellido": "Gilliam",
            "email": "eatongilliam@snorus.com",
            "telefono": "(916) 543-2619",
            "direccion": "79 Adelphi Street",
            "ciudad": "Independence",
            "contratacion": "1991-07-28",
            "departamento": "marketing"
        },
        {
            "salario": "$1,489.00",
            "edad": 34,
            "nombre": "Crystal",
            "apellido": "Talley",
            "email": "crystaltalley@snorus.com",
            "telefono": "(973) 499-2780",
            "direccion": "48 Lawn Court",
            "ciudad": "Nogal",
            "contratacion": "1997-03-01",
            "departamento": "desarrollo"
        },
        {
            "salario": "$8,954.00",
            "edad": 28,
            "nombre": "Mattie",
            "apellido": "Byers",
            "email": "mattiebyers@snorus.com",
            "telefono": "(815) 412-2532",
            "direccion": "61 Jerome Street",
            "ciudad": "Sunbury",
            "contratacion": "1996-11-17",
            "departamento": "arquitectura"
        },
        {
            "salario": "$1,156.00",
            "edad": 31,
            "nombre": "Josefa",
            "apellido": "David",
            "email": "josefadavid@snorus.com",
            "telefono": "(997) 555-2942",
            "direccion": "56 Howard Alley",
            "ciudad": "Sparkill",
            "contratacion": "1989-08-05",
            "departamento": "desarrollo"
        },
        {
            "salario": "$2,468.00",
            "edad": 24,
            "nombre": "Kramer",
            "apellido": "Mcconnell",
            "email": "kramermcconnell@snorus.com",
            "telefono": "(866) 498-2115",
            "direccion": "86 Classon Avenue",
            "ciudad": "Virgie",
            "contratacion": "1993-10-24",
            "departamento": "gerencia"
        },
        {
            "salario": "$7,018.00",
            "edad": 39,
            "nombre": "Mia",
            "apellido": "Sears",
            "email": "miasears@snorus.com",
            "telefono": "(812) 562-2109",
            "direccion": "64 Tudor Terrace",
            "ciudad": "Sabillasville",
            "contratacion": "2007-03-13",
            "departamento": "marketing"
        },
        {
            "salario": "$3,974.00",
            "edad": 36,
            "nombre": "Claudine",
            "apellido": "Cochran",
            "email": "claudinecochran@snorus.com",
            "telefono": "(900) 509-2606",
            "direccion": "53 Monument Walk",
            "ciudad": "Williamson",
            "contratacion": "2001-01-02",
            "departamento": "arquitectura"
        },
        {
            "salario": "$3,023.00",
            "edad": 29,
            "nombre": "Drake",
            "apellido": "Higgins",
            "email": "drakehiggins@snorus.com",
            "telefono": "(825) 515-3819",
            "direccion": "88 Matthews Place",
            "ciudad": "Walton",
            "contratacion": "2013-03-29",
            "departamento": "gerencia"
        },
        {
            "salario": "$7,675.00",
            "edad": 25,
            "nombre": "Cole",
            "apellido": "Camacho",
            "email": "colecamacho@snorus.com",
            "telefono": "(986) 555-2303",
            "direccion": "38 Lorraine Street",
            "ciudad": "Eastmont",
            "contratacion": "1986-11-22",
            "departamento": "marketing"
        },
        {
            "salario": "$5,238.00",
            "edad": 21,
            "nombre": "Eve",
            "apellido": "Kelley",
            "email": "evekelley@snorus.com",
            "telefono": "(944) 494-2263",
            "direccion": "43 Harden Street",
            "ciudad": "Kenmar",
            "contratacion": "1993-01-28",
            "departamento": "gerencia"
        },
        {
            "salario": "$7,426.00",
            "edad": 29,
            "nombre": "Berry",
            "apellido": "Stephens",
            "email": "berrystephens@snorus.com",
            "telefono": "(886) 495-3894",
            "direccion": "20 Aurelia Court",
            "ciudad": "Blende",
            "contratacion": "2001-02-11",
            "departamento": "arquitectura"
        },
        {
            "salario": "$7,890.00",
            "edad": 44,
            "nombre": "Lara",
            "apellido": "Fuentes",
            "email": "larafuentes@snorus.com",
            "telefono": "(859) 400-3192",
            "direccion": "74 Wallabout Street",
            "ciudad": "Dale",
            "contratacion": "2006-09-18",
            "departamento": "gerencia"
        },
        {
            "salario": "$1,318.00",
            "edad": 35,
            "nombre": "Morrison",
            "apellido": "Jimenez",
            "email": "morrisonjimenez@snorus.com",
            "telefono": "(954) 469-2013",
            "direccion": "68 Story Court",
            "ciudad": "Holtville",
            "contratacion": "2001-08-06",
            "departamento": "arquitectura"
        },
        {
            "salario": "$6,187.00",
            "edad": 42,
            "nombre": "Cherry",
            "apellido": "French",
            "email": "cherryfrench@snorus.com",
            "telefono": "(996) 521-2169",
            "direccion": "11 Linden Street",
            "ciudad": "Whitmer",
            "contratacion": "1991-07-19",
            "departamento": "desarrollo"
        },
        {
            "salario": "$8,091.00",
            "edad": 27,
            "nombre": "Lawrence",
            "apellido": "Ferrell",
            "email": "lawrenceferrell@snorus.com",
            "telefono": "(810) 473-2281",
            "direccion": "42 Anchorage Place",
            "ciudad": "Nadine",
            "contratacion": "1991-07-02",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$1,922.00",
            "edad": 27,
            "nombre": "Sims",
            "apellido": "Hamilton",
            "email": "simshamilton@snorus.com",
            "telefono": "(850) 549-2421",
            "direccion": "97 Lefferts Avenue",
            "ciudad": "Bellfountain",
            "contratacion": "2002-08-18",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$5,648.00",
            "edad": 26,
            "nombre": "Holden",
            "apellido": "Tran",
            "email": "holdentran@snorus.com",
            "telefono": "(911) 524-3286",
            "direccion": "42 Vermont Street",
            "ciudad": "Washington",
            "contratacion": "2000-04-06",
            "departamento": "marketing"
        },
        {
            "salario": "$6,257.00",
            "edad": 46,
            "nombre": "Sharron",
            "apellido": "Deleon",
            "email": "sharrondeleon@snorus.com",
            "telefono": "(962) 565-2130",
            "direccion": "85 Benson Avenue",
            "ciudad": "Interlochen",
            "contratacion": "1992-03-08",
            "departamento": "gerencia"
        },
        {
            "salario": "$2,332.00",
            "edad": 48,
            "nombre": "Alicia",
            "apellido": "Leon",
            "email": "alicialeon@snorus.com",
            "telefono": "(842) 599-2389",
            "direccion": "56 Harbor Court",
            "ciudad": "Sandston",
            "contratacion": "2008-03-25",
            "departamento": "marketing"
        },
        {
            "salario": "$8,848.00",
            "edad": 21,
            "nombre": "Foreman",
            "apellido": "Mcintosh",
            "email": "foremanmcintosh@snorus.com",
            "telefono": "(968) 586-3584",
            "direccion": "45 Court Street",
            "ciudad": "Madrid",
            "contratacion": "2008-05-16",
            "departamento": "marketing"
        },
        {
            "salario": "$2,284.00",
            "edad": 28,
            "nombre": "James",
            "apellido": "Massey",
            "email": "jamesmassey@snorus.com",
            "telefono": "(889) 406-2226",
            "direccion": "67 School Lane",
            "ciudad": "Moraida",
            "contratacion": "1986-01-20",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$8,133.00",
            "edad": 52,
            "nombre": "Corrine",
            "apellido": "Mercer",
            "email": "corrinemercer@snorus.com",
            "telefono": "(810) 444-3042",
            "direccion": "45 Sedgwick Place",
            "ciudad": "Johnsonburg",
            "contratacion": "1987-12-25",
            "departamento": "desarrollo"
        },
        {
            "salario": "$7,743.00",
            "edad": 54,
            "nombre": "Elizabeth",
            "apellido": "Henry",
            "email": "elizabethhenry@snorus.com",
            "telefono": "(929) 537-3086",
            "direccion": "42 Noble Street",
            "ciudad": "Jennings",
            "contratacion": "2010-10-25",
            "departamento": "marketing"
        },
        {
            "salario": "$3,916.00",
            "edad": 35,
            "nombre": "Perez",
            "apellido": "Briggs",
            "email": "perezbriggs@snorus.com",
            "telefono": "(905) 557-2392",
            "direccion": "1 Wyckoff Avenue",
            "ciudad": "Crown",
            "contratacion": "1989-05-24",
            "departamento": "marketing"
        },
        {
            "salario": "$7,830.00",
            "edad": 48,
            "nombre": "Moon",
            "apellido": "Mcneil",
            "email": "moonmcneil@snorus.com",
            "telefono": "(844) 571-3441",
            "direccion": "19 Beard Street",
            "ciudad": "Vincent",
            "contratacion": "2007-08-30",
            "departamento": "desarrollo"
        },
        {
            "salario": "$8,478.00",
            "edad": 22,
            "nombre": "Nola",
            "apellido": "Bowman",
            "email": "nolabowman@snorus.com",
            "telefono": "(930) 581-3939",
            "direccion": "42 Hendrickson Place",
            "ciudad": "Welda",
            "contratacion": "1993-03-19",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$5,852.00",
            "edad": 51,
            "nombre": "Reva",
            "apellido": "Haney",
            "email": "revahaney@snorus.com",
            "telefono": "(844) 458-2928",
            "direccion": "49 Lacon Court",
            "ciudad": "Sunwest",
            "contratacion": "1992-11-13",
            "departamento": "recursos humanos"
        },
        {
            "salario": "$1,038.00",
            "edad": 33,
            "nombre": "Jackson",
            "apellido": "Cash",
            "email": "jacksoncash@snorus.com",
            "telefono": "(878) 564-3777",
            "direccion": "17 Hendrickson Street",
            "ciudad": "Soham",
            "contratacion": "1983-12-09",
            "departamento": "gerencia"
        },
        {
            "salario": "$3,764.00",
            "edad": 26,
            "nombre": "Bass",
            "apellido": "Guthrie",
            "email": "bassguthrie@snorus.com",
            "telefono": "(890) 587-2376",
            "direccion": "50 Lincoln Road",
            "ciudad": "Stevens",
            "contratacion": "2011-04-27",
            "departamento": "arquitectura"
        },
        {
            "salario": "$4,397.00",
            "edad": 33,
            "nombre": "Kay",
            "apellido": "Kent",
            "email": "kaykent@snorus.com",
            "telefono": "(939) 453-3204",
            "direccion": "61 Trucklemans Lane",
            "ciudad": "Newkirk",
            "contratacion": "1987-07-29",
            "departamento": "desarrollo"
        }
    ];

    DataResource.setUrl(url);
    DataResource.setRequestParams(apiKeyParam);

    $scope.mensajes = ['Cargando registros'];

    angular.forEach(insert, function(value, key){
        DataResource.save(value).then(function(){
            $scope.mensajes.push('Insertado registro ' + key + ' con valor: ' + JSON.stringify(value));
        }, function(){
            $scope.mensajes = 'ocurrió un error en registro ' + key + ' con valor: ' + JSON.stringify(value);
        });
    });
});